export {default as Login} from './Login'
export {default as Signup} from './Signup'
export {default as Auth} from './Auth'
export {default as Update} from './Update'
export {default as Dark} from './Dark'
export {default as Signout} from './Signout'
export {default as Password} from './Password'
